# Site settings
title: JD Foodie
email: jessicamdearr@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jdfoodie.com" # the base hostname & protocol for your site
paginate: 12
paginate_path: "/blog/page:num"
asset_url: "http://jdfoodie.com"

# Build settings
markdown: kramdown

exclude: 
  - Rakefile
  - README.md
  - Gemfile
  - Gemfile.lock
  - s3_website.yml

# To run locally:
# bundle exec jekyll serve --force_polling -w