# Site settings
title: JD Foodie
email: jessicamdearr@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site


# Build settings
markdown: kramdown

exclude: 
  - Rakefile
  - README.md
  - Gemfile
  - Gemfile.lock
  - s3_website.yml

# To run locally:
# bundle exec jekyll serve --force_polling -w